[memory]
# initialize memory segments
initialize = true
# clear stack after pop or other similar operations
stack.clear = true
[memory.segment-addresses]
#Set min max for each memory segment
stack = { min = 256, max = 299 }
local = { min = 256, max = 399 }
arg = { min = 256, max = 499 }
this = { min = 3000, max = 3009 }
that = { min = 3010, max = 4000 }
pointer = { min = 3, max = 4 }
temp = { min = 5, max = 12 }
static = { min = 16, max = 255 }